# Generated by Django 2.2.1 on 2019-10-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0023_auto_20191029_2324'),
        ('discounts', '0002_auto_20191010_1641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refund amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('note', models.TextField(blank=True, null=True, verbose_name='refund reason')),
                ('reference_no', models.CharField(default=payments.models.increment_refund_reference, max_length=50, unique=True, verbose_name='reference no')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='refunded by')),
                ('enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Enrolled')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('payment_type', models.CharField(choices=[('stripe', 'Online Payment (Stripe)'), ('cash', 'Cash'), ('money-transfer', 'Money Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='stripe', max_length=50, verbose_name='payment type')),
                ('reference_no', models.CharField(default=payments.models.increment_reference_number, max_length=50, unique=True, verbose_name='reference no')),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='cheque no')),
                ('applied_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount')),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount owed')),
                ('has_applied_discount', models.BooleanField(default=False, verbose_name='has applied discount')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.Discount', verbose_name='discount code')),
                ('enrolled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.Enrolled')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
