# Generated by Django 2.2.1 on 2019-07-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='enrolled',
        ),
    ]
