# Generated by Django 2.2.1 on 2019-08-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrolled_status'),
        ('payments', '0003_auto_20190717_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='course',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Enrolled'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(default='stripe', max_length=50, verbose_name='payment type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='reference_no',
            field=models.CharField(max_length=50, null=True, verbose_name='reference no'),
        ),
    ]
