# Generated by Django 2.2.1 on 2019-08-23 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190822_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Enrolled'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('bank-transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='stripe', max_length=50, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reference no'),
        ),
    ]
