# Generated by Django 2.2.1 on 2019-10-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20191011_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_type',
            field=models.CharField(choices=[('stripe', 'Online Payment (Stripe)'), ('cash', 'Cash'), ('money-transfer', 'Money Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='stripe', max_length=50, verbose_name='payment type'),
        ),
    ]
