# Generated by Django 2.2.1 on 2019-10-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20191011_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='cheque no'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='reference_no',
            field=models.CharField(default='test_ref', max_length=50, verbose_name='reference no'),
            preserve_default=False,
        ),
    ]
