# Generated by Django 2.2.1 on 2019-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20191011_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='reference_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='reference no'),
        ),
    ]
