# Generated by Django 2.2.1 on 2019-10-11 20:58

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20191011_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='reference_no',
            field=models.CharField(default=payments.models.increment_reference_number, max_length=50, unique=True, verbose_name='reference no'),
        ),
    ]
