# Generated by Django 2.2.1 on 2019-10-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20191010_1641'),
        ('payments', '0010_auto_20191011_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='applied_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='applied discount'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.Discount'),
        ),
    ]
