# Generated by Django 2.2.1 on 2019-10-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20191014_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='amount_left',
            field=models.FloatField(blank=True, null=True, verbose_name='amount due'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount_paid',
            field=models.FloatField(default=0, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='applied_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.Discount', verbose_name='discount code'),
        ),
    ]
