# Generated by Django 2.2.1 on 2019-10-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20191015_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='amount_left',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='amount_owed',
            field=models.FloatField(blank=True, null=True, verbose_name='amount owed'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.Enrolled'),
        ),
    ]
