# Generated by Django 2.2.1 on 2019-10-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20191015_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='has_applied_discount',
            field=models.BooleanField(default=False, verbose_name='has applied discount'),
        ),
    ]
