# Generated by Django 2.2.1 on 2019-10-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_paymentlog_has_applied_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='amount_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount owed'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='applied_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount'),
        ),
    ]
