# Generated by Django 2.2.1 on 2019-10-16 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20191016_0357'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0015_auto_20191016_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('reference_no', models.CharField(default=payments.models.increment_refund_reference, max_length=50, unique=True, verbose_name='reference no')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Enrolled')),
            ],
        ),
    ]
