# Generated by Django 2.2.1 on 2019-10-20 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='refund amount'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='refunded by'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='refund reason'),
        ),
    ]
