# Generated by Django 2.2.1 on 2019-07-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'administrator', 'verbose_name_plural': 'administrators'},
        ),
    ]
