# Generated by Django 2.2.1 on 2019-08-28 10:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190822_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.FileField(null=True, upload_to=users.models.identity_document_path, verbose_name='identification'),
        ),
    ]
