# Generated by Django 2.2.1 on 2019-09-04 10:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.FileField(null=True, upload_to=users.models.identity_document_path, verbose_name='identification document'),
        ),
    ]
