# Generated by Django 2.2 on 2019-05-30 10:38

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('course_fee', models.FloatField(verbose_name='course fee')),
                ('image', models.ImageField(upload_to=courses.models.course_image_path, verbose_name='image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partly', 'Part Payment'), ('paid', 'Fully Paid')], max_length=50)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.IntegerField(verbose_name='order')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
        migrations.CreateModel(
            name='UserModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date_activated', models.DateTimeField(auto_now_add=True, verbose_name='date activated')),
                ('expires', models.DateTimeField(verbose_name='date expires')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='courses.Courses')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Modules')),
            ],
        ),
    ]
