# Generated by Django 2.2 on 2019-04-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('fees', models.FloatField(verbose_name='fees')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('access_url', models.CharField(max_length=50, verbose_name='access url')),
                ('order', models.IntegerField(verbose_name='order')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='UserModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('date_activated', models.DateTimeField(auto_now_add=True, verbose_name='date activated')),
                ('expires', models.DateTimeField(verbose_name='date expires')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to='courses.Courses')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Modules')),
            ],
        ),
    ]
