# Generated by Django 2.2.1 on 2019-05-30 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190530_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='access_code',
            field=models.CharField(default='BUST1234!', max_length=100, verbose_name='media code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodules',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
