# Generated by Django 2.2.1 on 2019-06-29 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20190530_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolled',
            options={'verbose_name': 'Enrolled Course', 'verbose_name_plural': 'Enrolled Courses'},
        ),
        migrations.AddField(
            model_name='enrolled',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount paid'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='course fee'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolled',
            unique_together={('course', 'user')},
        ),
    ]
