# Generated by Django 2.2.1 on 2019-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_enrolled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
