# Generated by Django 2.2.1 on 2019-09-04 10:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_enrolled_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='course_code'),
        ),
        migrations.AddField(
            model_name='courses',
            name='outline',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='outline'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='description'),
        ),
    ]
