# Generated by Django 2.2.1 on 2019-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190904_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodules',
            name='days',
            field=models.IntegerField(default=7, verbose_name='open for'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='course code'),
        ),
    ]
