# Generated by Django 2.2.1 on 2019-09-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190909_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.TextField(default='This course is instructor led, provides audience with the required technical skills to write T-SQL queries for Microsoft SQL Server. This course is the foundation for all SQL Server-related disciplines; namely, Database Administration, Database Development and Business Intelligence.', verbose_name='overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='pre_requisites',
            field=models.TextField(default='Basic knowledge of the Microsoft Windows operating system and its core functionality Preferred but not mandatory to have knowledge of relational databases.', verbose_name='pre-requisites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='strategy',
            field=models.TextField(blank=True, null=True, verbose_name='strategy'),
        ),
        migrations.AddField(
            model_name='courses',
            name='tools_and_technology',
            field=models.TextField(blank=True, null=True, verbose_name='tools and technologies'),
        ),
    ]
