# Generated by Django 2.2.1 on 2019-09-18 11:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190917_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='learning_and_outcome',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='learning and outcome'),
        ),
    ]
