# Generated by Django 2.2.1 on 2019-10-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190923_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_fee',
        ),
        migrations.AddField(
            model_name='courses',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='base fee'),
            preserve_default=False,
        ),
    ]
