# Generated by Django 2.2.1 on 2019-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20191014_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='payment_status',
            field=models.CharField(choices=[('partly', 'Part Payment'), ('paid', 'Fully Paid')], default='paid', max_length=50),
        ),
    ]
