# Generated by Django 2.2.1 on 2019-10-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20191015_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=50),
        ),
    ]
