# Generated by Django 2.2.1 on 2019-10-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20191010_1641'),
        ('courses', '0020_auto_20191016_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEnrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number')),
                ('payment_type', models.CharField(choices=[('partial', 'Part Payment'), ('full', 'Full Payment')], max_length=10, null=True)),
                ('payment_status', models.CharField(choices=[('partly', 'Part Payment'), ('paid', 'Fully Paid')], max_length=50, null=True)),
                ('applied_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount')),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount owed')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.Discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
