# Generated by Django 2.2.1 on 2019-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_pendingenrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingenrollments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='amount paid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingenrollments',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=50, null=True),
        ),
    ]
