# Generated by Django 2.2.1 on 2019-10-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20191029_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingenrollments',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pendingenrollments',
            name='amount_owed',
        ),
        migrations.RemoveField(
            model_name='pendingenrollments',
            name='applied_discount',
        ),
    ]
